"""latency, trade microstructure, ensembles and sweeps Revision ID: eab3e1140eb3 Revises."""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eab3e1140eb3'
down_revision: Union[str, None] = '155be5af5848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust!
    op.create_table('ensembles',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_seed', sa.Integer(), nullable=False),
    sa.Column('path_count', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('shared_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('engine_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_paths', sa.Integer(), nullable=False),
    sa.Column('aggregates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('paths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sweeps',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grid_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('shared_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pbo', sa.Float(), nullable=True),
    sa.Column('best_cell', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('robust_centroid', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trial_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sweep_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sweep_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('in_sample_sharpe', sa.Float(), nullable=True),
    sa.Column('out_of_sample_sharpe', sa.Float(), nullable=True),
    sa.Column('deflated_sharpe', sa.Float(), nullable=True),
    sa.Column('in_sample_pnl', sa.Float(), nullable=True),
    sa.Column('out_of_sample_pnl', sa.Float(), nullable=True),
    sa.Column('trial_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sweep_id'], ['sweeps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sweep_results', schema=None) as batch_op:
        batch_op.create_index('ix_sweep_results_sweep', ['sweep_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        # Existing agents predate latency, and an empty object means "no delay" - which is exactly.
        batch_op.add_column(sa.Column('latency_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ensemble_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True))
        batch_op.add_column(sa.Column('path_index', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_simulations_ensemble_id_ensembles', 'ensembles', ['ensemble_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mid_at_trade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('effective_half_spread', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('realised_half_spread', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_impact', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('horizon_steps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust!
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('horizon_steps')
        batch_op.drop_column('price_impact')
        batch_op.drop_column('realised_half_spread')
        batch_op.drop_column('effective_half_spread')
        batch_op.drop_column('mid_at_trade')

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_simulations_ensemble_id_ensembles', type_='foreignkey')
        batch_op.drop_column('path_index')
        batch_op.drop_column('ensemble_id')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('latency_config')

    with op.batch_alter_table('sweep_results', schema=None) as batch_op:
        batch_op.drop_index('ix_sweep_results_sweep')

    op.drop_table('sweep_results')
    op.drop_table('sweeps')
    op.drop_table('ensembles')
    # ### end Alembic commands ###
